import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Text } from "@chakra-ui/react";
import dynamic from "next/dynamic";
const MyAwesomeMap = dynamic(() => import("@/components/Map"), {
  ssr: false,
});
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.layout}`}>
        <Text fontSize="6xl" textAlign="center">
          {" "}
          Calculate cost to travel
        </Text>
        <div className={`${styles.mapContainer}`}>
          <MyAwesomeMap />
        </div>
      </main>
    </>
  );
}
